apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: simple-webapp
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            env: prod
        values:
          branch: main
  template:
    metadata:
      name: "{{name}}-simple-webapp"
      annotations:
        argocd.argoproj.io/manifest-generate-paths: ".;.."
      spec:
        project: default
        sources:
          - repoURL: git@github.com:lcavanzo/gitops-study.git
            targetRevision: "{{values.branch}}"
            path: ./implementing_gitops_book/ch05/chapter-5-the-app-of-apps-approach/applicationsets/simple-webapp
        destination:
          name: "{{name}}"
          namespace: "argocd"
          syncOptions:
            - CreateNamespace=true
