apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-city-weather-app
  namespace: argocd
spec:
  destination:
    namespace: gitops-kubernetes
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/lcavanzo/gitops_study.git
    path: ./implementing_gitops_book/ch04/argocd_gitops/deployment/
    targetRevision: main
