apiVersion: v1
kind: Namespace
metadata:
  name: gitops-kubernetes
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-cd-pipeline-deployment
  namespace: gitops-kubernetes
  labels:
    app: first-cd-pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: first-cd-pipeline
  template:
    metadata:
      labels:
        app: first-cd-pipeline
    spec:
      containers:
        - name: first-cd-pipeline
          image: lcavanzo/hello-world-py-app:2.0
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: first-cd-pipeline-service
  namespace: gitops-kubernetes
spec:
  type: NodePort
  selector:
    app: first-cd-pipeline
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30007
