# Use an official Node.js runtime as a parent image
FROM node:14

# Set the working directory
WORKDIR /usr/src/app

# Copy package.json and install dependencies
COPY ./implementing_gitops_book/ch04/argocd_gitops/package*.json ./
RUN npm install

# Bundle app source
COPY ./implementing_gitopl_book/ch04/argocd_gitops/src/ .

# Expose the port the app runs on
EXPOSE 3000

# Define the command to run the app
CMD ["node", "server.js"]
