apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-city-weather-app
  labels:
    app: my-city-weather-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-city-weather-app
  template:
    metadata:
      labels:
        app: my-city-weather-app
    spec:
      containers:
        - name: my-city-weather-app
          image: lcavanzo/gitops-k8s-deployments:main
          ports:
            - containerPort: 8080
          # resources:
          #   requests:
          #     memory: "64Mi"
          #     cpu: "250m"
          #   limits:
          #     memory: "128Mi"
          #     cpu: "500m"
