apiVersion: v1
kind: Service
metadata:
  name: my-city-weather-app-service
spec:
  selector:
    app: my-city-weather-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30007
