name: Create Docker Image CI

on:
  push:
    branches:
      # - "main"
      - "release"

  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1

      - name: Build the Docker image

        run: docker build . --file ./implementing_gitops_book/ch02/docker-hello-world/Dockerfile --tag my-image-name:$(date +%s)
